[project]
name = "braw-brew"
version = "1.0.0"
description = "BRAW-Brew: Distributed BRAW rendering system"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "psutil>=7.1.3",
    "pyside6>=6.10.1",
    "pyinstaller>=6.0",
]
